AWSTemplateFormatVersion: 2010-09-09

Description: >-
  crypto-bot-bloodhound

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  LogLevelParameter:
    Type: String
    Description: Functions log level
    Default: info
    AllowedValues:
      - debug
      - info
  EnvironmentParameter:
    Type: String
    Description: Environment where the stack is deployed
    Default: prod
    AllowedValues:
      - prod
  TracingParameter:
    Description: Boolean to enable or disable tracing
    Type: String
    Default: false
  ExchangesSecretNameParameter:
    Description: Name of the exchanges secret stored in Secrets Manager
    Type: String
  ExchangesSecretEncryptionKeyParameter:
    Description: Encryption key used to encrypt the exchanges secret in Secrets Manager (either a key id 'key/xxx' or an alias 'alias/xxx')
    Type: String
    Default: alias/aws/secretsmanager
  PhoneNumbersParameter:
    Description: List of phone numbers separated by comma to send a SMS for each new coin listing (E.164 format)
    Type: String
  QuoteAssetParameter:
    Description: Quote asset to use in trading pair
    Type: String
  QuoteAssetQuantityParameter:
    Description: Quote asset quantity to trade
    Type: Number
  RetryIntervalMillisecondsParameter:
    Description: Retry interval in milliseconds between attempts
    Type: Number
    Default: 1000

Conditions:
  TracingCondition: !Equals [ !Ref TracingParameter, true ]

Mappings:
  EnvironmentMap:
    prod:
      ScanCoinListingSchedule: rate(10 minutes)

Globals:
  Function:
    Runtime: nodejs16.x
    MemorySize: 128
    Timeout: 30
    AutoPublishAlias: Live
    Tracing: !If [ TracingCondition, Active, PassThrough ]
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevelParameter
        ENV: !Ref EnvironmentParameter
        REGION: !Ref AWS::Region
        TRACING: !Ref TracingParameter

Resources:
  ScanCoinListingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Scan coin listing function
      CodeUri: src/handlers
      Handler: scan-coin-listing-handler.handler
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          COIN_LISTING_TABLE_NAME: !Ref CoinListingTable
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: !FindInMap [ EnvironmentMap, !Ref EnvironmentParameter, ScanCoinListingSchedule ]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CoinListingTable
        - DynamoDBWritePolicy:
            TableName: !Ref CoinListingTable
        - EventBridgePutEventsPolicy:
            EventBusName: default
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2021
        Minify: true
        SourceMap: true
        EntryPoints:
          - scan-coin-listing-handler.ts

  NotifyCoinListingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Notify coin listing function
      CodeUri: src/handlers
      Handler: notify-coin-listing-handler.handler
      Environment:
        Variables:
          PHONE_NUMBERS: !Ref PhoneNumbersParameter
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource:
                - '*'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2021
        Minify: true
        SourceMap: true
        EntryPoints:
          - notify-coin-listing-handler.ts

  TradeCoinListingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Trade coin listing function
      CodeUri: src/handlers
      Handler: trade-coin-listing-handler.handler
      MemorySize: 2048
      Timeout: 60
      Environment:
        Variables:
          EXCHANGES_SECRET_NAME: !Ref ExchangesSecretNameParameter
          QUOTE_ASSET: !Ref QuoteAssetParameter
          QUOTE_ASSET_QUANTITY: !Ref QuoteAssetQuantityParameter
          RETRY_INTERVAL_MILLISECONDS: !Ref RetryIntervalMillisecondsParameter
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ExchangesSecretNameParameter}*
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${ExchangesSecretEncryptionKeyParameter}
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2021
        Minify: true
        SourceMap: true
        EntryPoints:
          - trade-coin-listing-handler.ts

  CoinListingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      DefinitionUri: aws/coin-listing-state-machine.json
      DefinitionSubstitutions:
        NotifyCoinListingFunctionArn: !GetAtt NotifyCoinListingFunction.Arn
        TradeCoinListingFunctionArn: !GetAtt TradeCoinListingFunction.Arn
      Events:
        EventBridgeRuleEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - hastobegood.cryptobotbloodhound
              detail-type:
                - NewCoinListing
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifyCoinListingFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref TradeCoinListingFunction

  CoinListingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  ScanCoinListingFunctionName:
    Description: Scan coin listing function name
    Value: !Ref ScanCoinListingFunction
  ScanCoinListingFunctionArn:
    Description: Scan coin listing function ARN
    Value: !GetAtt ScanCoinListingFunction.Arn

  NotifyCoinListingFunctionName:
    Description: Notify coin listing function name
    Value: !Ref NotifyCoinListingFunction
  NotifyCoinListingFunctionArn:
    Description: Notify coin listing function ARN
    Value: !GetAtt NotifyCoinListingFunction.Arn

  TradeCoinListingFunctionName:
    Description: Trade coin listing function name
    Value: !Ref TradeCoinListingFunction
  TradeCoinListingFunctionArn:
    Description: Trade coin listing function ARN
    Value: !GetAtt TradeCoinListingFunction.Arn

  CoinListingStateMachineArn:
    Description: Coin listing state machine ARN
    Value: !Ref CoinListingStateMachine
  CoinListingStateMachineName:
    Description: Coin listing state machine name
    Value: !GetAtt CoinListingStateMachine.Name

  CoinListingTableName:
    Description: Coin listing table name
    Value: !Ref CoinListingTable
  CoinListingTableArn:
    Description: Coin listing table ARN
    Value: !GetAtt CoinListingTable.Arn
